1-й коммит
T0nystoyz/java-explore-with-me pull request #1
Opened 2022-10-30 13:22 UTC by T0nystoyz

2022-11-03 20:58 UTC, alexache requested changes

2022-11-03 20:58 UTC, alexache commented on .gitignore
> +/java-explore-with-me.zip
Какие-то зип файлы все равно просочились

2022-11-03 20:58 UTC, alexache commented on main_server/pom.xml
> +			<version>42.5.0</version>
Версии зависимостец желательно задать в родительском модуле через dependencyManagement

2022-11-03 20:58 UTC, alexache commented on main_server/pom.xml
> +			<version>3.10.8</version>
И все последующие версии тоже

2022-11-03 20:58 UTC, alexache commented on stats_server/pom.xml
> +			<version>42.5.0</version>
Такой же комментарий про версии зависимостей, как и в другом сервисе

2022-11-03 20:58 UTC, alexache commented on stats_server/src/main/java/ru/practicum/stats_server/model/EndpointHit.java
> +    @Override
Этих методов не должно быть в модели, плохо сочетается с Hibernate

2022-11-03 20:58 UTC, alexache commented on stats_server/src/main/java/ru/practicum/stats_server/controller/StatisticController.java
> +    public EndpointHit createHit(@RequestBody @Valid EndpointHit endpointHit) {
Лучше разделить модель и дто на два разных класса, чтобы добавлять валидации отдельно от модели

2022-11-03 20:58 UTC, alexache commented on stats_server/src/main/java/ru/practicum/stats_server/service/StatisticService.java
> +        startTime = LocalDateTime.parse(decodeStart, DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss") можно бы вынести в константу-поле класса

2022-11-03 20:58 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/client/StatisticClient.java
> +                "start", URLEncoder.encode(start.format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")), StandardCharsets.UTF_8.toString()),
DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss") можно сделать константой-полем класса

2022-11-03 20:58 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/exception/ErrorHandlingControllerAdvice.java
> +@RestController
Для чего здесь эта аннотация?

2022-11-03 20:58 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/model/Category.java
> +    public boolean equals(Object o) {
Лишние методы в модели

2022-11-03 20:58 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/model/dto/AdminUpdateEventRequest.java
> +    private String annotation;
Может стоит добавить валидаций и здесь?

2022-11-03 20:58 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/model/dto/CategoryDto.java
> +    private String name;
Валидации не помешают для ДТО

2022-11-03 20:58 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/service/admin_service/AdminCategoryService.java
> +        categoryRepository.save(toCategoryFromCategoryDto(categoryDto));
Для чего 2 вызова метода save и вызов getReferenceById?

2022-11-03 20:58 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/service/admin_service/AdminCompilationService.java
> +                .map(eventRepository::getReferenceById)
То есть получаются 2 вызова получения ивентов по айди?

2022-11-03 20:58 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/service/admin_service/AdminCompilationService.java
> +        checkCompilationInDb(compId);
Все эти check зачастую лишние запросы, вместо одного запроса получения делается 2, но чем это лучше?

2022-11-03 20:58 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/service/admin_service/AdminCompilationService.java
> +    private CompilationDto setViewsAndConfirmedRequests(CompilationDto compilationDto) {
А это точно необходимо?

2022-11-03 20:58 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/service/admin_service/AdminEventService.java
> +                .map(this::setConfirmedRequestsAndViews)
Точно ли нужен этот шаг, потому что запросы к базе в цикле - это очень плохо

2022-11-03 20:58 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/service/admin_service/AdminEventService.java
> +        return setConfirmedRequestsAndViews(eventFullDto);
Как и здесь

2022-11-03 20:58 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/service/private_service/PrivateEventService.java
> +        if (Objects.equals(responseEntity.getBody(), "")) {
Интересный способ работы с json объектом

2022-11-03 20:58 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/service/public_service/PublicCompilationService.java
> +                .map(eventService::setConfirmedRequestsAndViewsEventShortDto)
Тоже не уверен, что нужно, еще и в цикле

2022-11-03 20:58 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/service/public_service/PublicEventService.java
> +                            <= eventRepository.getReferenceById(eventShortDto.getId()).getParticipantLimit())
Зачем снова запращивать событие, если эта инфомрация было в списке events?

2022-11-04 06:52 UTC, T0nystoyz commented on .gitignore
> +/java-explore-with-me.zip
могу убрать, но разве это плохо, что эти файлы в гитигнор? они ведь не в проекте висят без дела

2022-11-04 08:41 UTC, T0nystoyz commented on main_server/pom.xml
> +			<version>42.5.0</version>
сделано

2022-11-04 09:06 UTC, T0nystoyz commented on stats_server/src/main/java/ru/practicum/stats_server/controller/StatisticController.java
> +    public EndpointHit createHit(@RequestBody @Valid EndpointHit endpointHit) {
готово

2022-11-04 09:07 UTC, T0nystoyz commented on stats_server/src/main/java/ru/practicum/stats_server/service/StatisticService.java
> +        startTime = LocalDateTime.parse(decodeStart, DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
готово

2022-11-04 09:11 UTC, T0nystoyz commented on main_server/src/main/java/ru/practicum/main_server/client/StatisticClient.java
> +                "start", URLEncoder.encode(start.format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")), StandardCharsets.UTF_8.toString()),
готово

2022-11-04 09:13 UTC, T0nystoyz commented on main_server/src/main/java/ru/practicum/main_server/exception/ErrorHandlingControllerAdvice.java
> +@RestController
лишнее, перекочевала с прошлого проекта ошибка

2022-11-04 09:16 UTC, T0nystoyz commented on main_server/src/main/java/ru/practicum/main_server/model/Category.java
> +    public boolean equals(Object o) {
я так понимаю во всех моделях не нужны эти методы?

2022-11-04 09:56 UTC, T0nystoyz commented on main_server/src/main/java/ru/practicum/main_server/model/dto/CategoryDto.java
> +    private String name;
ок

2022-11-04 09:56 UTC, T0nystoyz commented on main_server/src/main/java/ru/practicum/main_server/model/dto/AdminUpdateEventRequest.java
> +    private String annotation;
Ну на нулл валидировать тут смысла нет, например, если поле не нулл, оно обновляется в сервисе. Разве что participationLimit зааннотировать @Positive, а в остальном как-то не вижу где стоит валидацию применить здесь.

2022-11-04 09:59 UTC, T0nystoyz commented on main_server/src/main/java/ru/practicum/main_server/service/admin_service/AdminCategoryService.java
> +        categoryRepository.save(toCategoryFromCategoryDto(categoryDto));
исправил. тут по задумке должен был быть метод check

2022-11-04 10:21 UTC, T0nystoyz commented on main_server/src/main/java/ru/practicum/main_server/service/admin_service/AdminCompilationService.java
> +    private CompilationDto setViewsAndConfirmedRequests(CompilationDto compilationDto) {
А почему нет? Согласно спецификации у событий должны быть кол-во просмотров и кол-во принятых запросов.

2022-11-04 12:41 UTC, T0nystoyz commented on main_server/src/main/java/ru/practicum/main_server/service/admin_service/AdminCompilationService.java
> +                .map(eventRepository::getReferenceById)
исправил

2022-11-04 12:42 UTC, T0nystoyz commented on main_server/src/main/java/ru/practicum/main_server/service/admin_service/AdminCompilationService.java
> +        checkCompilationInDb(compId);
заменил на методы getOrThrow

2022-11-04 13:26 UTC, T0nystoyz commented on main_server/src/main/java/ru/practicum/main_server/service/admin_service/AdminEventService.java
> +                .map(this::setConfirmedRequestsAndViews)
хорошим ли решением будет исправить эту ситуацию ручным инкрементированием нового поля confirmedRequests в моделях события при подтверждении запроса?

2022-11-06 06:51 UTC, alexache commented on .gitignore
> +/java-explore-with-me.zip
Я не к тому, что нужно что-то убрать их гитигнора. а к тому, что все равно в проекте попались зип файлы с немного другим именем, может стоит учесть их имена

2022-11-07 08:25 UTC, alexache commented on stats_server/src/main/java/ru/practicum/stats_server/dto/EndpointHitDto.java
> +    private Long id;
И можно добавить каких-то валидаций на поля

2022-11-07 08:25 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/service/admin_service/AdminEventService.java
> +                .map(this::setConfirmedRequestsAndViews)
Проблема не в том. что нужно делать, а в способе. То есть да, количество участников нужно получать из БД, но не в цикле по событиям. Это нужно писать отдельный запрос получения количества участников по списку событий в некий словарь, который уже потом использовать в формировании ответа. 
То есть осмновное правило - никаких запросов к БД в цикле. Отдельный запрос по большому списку событий - ок

2022-11-07 08:28 UTC, alexache requested changes

2022-11-07 08:28 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/service/admin_service/AdminEventService.java
> +                .peek(e -> e.setViews(getViews(e.getId())))
Запрос к серверсу статистики тоже лучше сделать 1 раз по всему списку событий, который хочется отсорировать. Писать запросы (к сервису/БД) выглядит наглядно и просто, но очень сильно влияет на производительность сервиса, Больше событий - больше время ответа

2022-11-07 16:36 UTC, T0nystoyz commented on main_server/src/main/java/ru/practicum/main_server/service/admin_service/AdminEventService.java
> +                .map(this::setConfirmedRequestsAndViews)
понял, спасибо за рекомендацию. уже переделал на инкремент, но буду знать

2022-11-09 19:50 UTC, alexache requested changes

2022-11-09 19:50 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/client/StatisticClient.java
> +                events.get(i).setViews(stats.get(i).getHits());
А порядок ViewStats точно гарантируется быть таким же, как и у событий? Мне кажется, это очень навряд ли. У ViewStats не зря есть свойство URI, то есть по ответу можно составить мапу URI -> количество просмотров и таким образом пройтись по списку событий и добавить количество просмотров по событиям

2022-11-09 19:50 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/controller/private_controller/PrivateEventController.java
> +    List<EventShortDto> readEvents(@PathVariable long userId,
Отсутствует модификатор доступа у метода

2022-11-09 19:50 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/controller/public_controller/PublicEventController.java
> +    List<EventShortDto> readEvents(@RequestParam(required = false) String text,
Отсутствует модификатор доступа у методов класса

2022-11-09 19:50 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/service/admin_service/AdminEventService.java
> +     * Возвращает время старта либо null
Текст комментария противоречит тому. что в реальности происходит. Комментарии стоит обновлять, чтобы не запутывали

2022-11-09 19:50 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/service/private_service/PrivateEventService.java
> +    public PrivateEventService(EventRepository eventRepository,
Может не помешает и @Autowired?

2022-11-09 19:50 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/service/private_service/PrivateParticipationRequestService.java
> +        event.setConfirmedRequests(event.getConfirmedRequests() + 1);
К сожалению, этот подход не самый лучший, нет никакой проверки, что нет какого-то другого потока, в котором тоже меняется количество участников из-за этого могут быть проблему консистентости

2022-11-09 20:02 UTC, T0nystoyz commented on main_server/src/main/java/ru/practicum/main_server/service/private_service/PrivateParticipationRequestService.java
> +        event.setConfirmedRequests(event.getConfirmedRequests() + 1);
через @Traansactioanal этого видимо не добиться? А какой есть выход? Кроме того что лезть в бд за подсчетом?

2022-11-10 22:07 UTC, alexache requested changes

2022-11-10 22:07 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/client/StatisticClient.java
> +                eventsMap.replace(id, e);
Лишняя операция, ты строчкой выше изменил обхект события, зачем его же заново добавлять в мапу?

2022-11-10 22:07 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/client/StatisticClient.java
> +                long id = Long.parseLong(entry.getKey().substring(entry.getKey().length() - 1));
Так, тут что-то сложное, это получение последнего знака в URL, чтобы найти id? А что если событий будет больше чем 9? Не проще ли в eventsMap сделать маппинг URI -> event, а URI не так сложно создать на основе eventId

2022-11-10 22:07 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/service/private_service/PrivateParticipationRequestService.java
> +    public synchronized ParticipationRequestDto approveParticipationRequest(Long userId, Long eventId, Long requestId) {
С распределенными сервисами все это уже бесполезно и только вызовет задержки

2022-11-10 22:07 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/service/public_service/PublicEventService.java
> +    private List<Event> getEventsWithConfirmedRequests(List<Event> events) {
Это прекрасно

2022-11-10 22:07 UTC, alexache commented on main_server/src/main/resources/application.properties
> +#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
закомментированные проперти лучше не оставлять

2022-11-10 22:07 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/model/Event.java
> +    private Long confirmedRequests;
А это поле еще нужно хранить в базе?

2022-11-10 22:12 UTC, T0nystoyz commented on main_server/src/main/java/ru/practicum/main_server/service/public_service/PublicEventService.java
> +    private List<Event> getEventsWithConfirmedRequests(List<Event> events) {
Сарказм?

2022-11-11 06:38 UTC, T0nystoyz commented on main_server/src/main/java/ru/practicum/main_server/client/StatisticClient.java
> +                eventsMap.replace(id, e);
точно, заплутал уже.

2022-11-11 06:44 UTC, T0nystoyz commented on main_server/src/main/java/ru/practicum/main_server/client/StatisticClient.java
> +                long id = Long.parseLong(entry.getKey().substring(entry.getKey().length() - 1));
спасибо за твою внимательность, не учел

2022-11-11 08:33 UTC, alexache commented on main_server/src/main/java/ru/practicum/main_server/service/public_service/PublicEventService.java
> +    private List<Event> getEventsWithConfirmedRequests(List<Event> events) {
@T0nystoyz кодекс ревьюера запрещает нам использовать сарказм. А если серьезно, то нет, это действительно решает задачу и всего лишь одним запросом к базе

2022-11-11 12:50 UTC, T0nystoyz commented on main_server/src/main/java/ru/practicum/main_server/service/public_service/PublicEventService.java
> +    private List<Event> getEventsWithConfirmedRequests(List<Event> events) {
спасибо)

2022-11-11 21:44 UTC, alexache approved these changes

2022-11-12 08:10 UTC, merged